# Generated by Django 5.2.1 on 2025-05-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_profile_faculty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
