# Generated by Django 5.2.1 on 2025-05-22 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0008_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
