# Generated by Django 5.2.1 on 2025-06-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year_of_study',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
