# Generated by Django 5.2.1 on 2025-06-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_profile_year_of_study'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='year_of_study',
            new_name='level',
        ),
    ]
