# Generated by Django 5.2.1 on 2025-05-22 12:50

import core.models
import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', shortuuid.django_fields.ShortUUIDField(alphabet='aid123', length=10, max_length=20, prefix='', unique=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('jamb_reg_number', models.CharField(max_length=50)),
                ('jamb_score', models.PositiveIntegerField()),
                ('jamb_document', models.FileField(default='default.pdf', upload_to=core.models.user_directory_path)),
                ('waec_document', models.FileField(default='default.pdf', upload_to=core.models.user_directory_path)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='core.course')),
            ],
        ),
    ]
